import React from "react";
import {
  Dashboard,
  History,
  AdminPanelSettings,
  Language,
  ViewCarousel,
  List,
  Layers,
  Source,
  Groups,
  Palette,
  Payment,
  SettingsApplications,
  Task,
  Work,
  Queue,
  Category,
  Camera,
  Slideshow,
  PictureAsPdf,
  Map,
  TextFormat,
  Inventory,
  Newspaper,
  Article,
  Markunread,
  MarkUnreadChatAlt,
  Sell,
  PaletteOutlined,
  PaletteSharp,
  LiveHelp,
  QuestionAnswer,
  ShoppingCart,
  OnlinePrediction,
  Star,
  Store,
  ShoppingBag,
  Search,
} from "@mui/icons-material";

// import settingsRoute from "../../../router/SettingsRoute";
import contentRoute from "components/router/ContentRoute";

const sideBarItem = [
  {
    id: 1,
    name: "Dashboard",
    description: "Dashboard",
    slug: "/",
    url: "/admin",
    icon: <Dashboard />,

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 2,
    name: "Latest Activity",
    description: "Latest Activity",
    slug: "activities",
    url: "/admin/activities",
    icon: <History />,

    list_order: 3,
    is_hidden: 0,
    is_done: 0,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 3,
    name: "Website",
    description: "",
    slug: "website",
    url: "/admin/activities/website",
    icon: <Language />,

    list_order: 1,
    is_hidden: 0,
    is_done: 0,
    parent_id: 2,
    url_parent_id: 2,
  },
  {
    id: 4,
    name: "Admin",
    description: "Admin",
    slug: "admin",
    url: "/admin/activities/admin",
    icon: <AdminPanelSettings />,

    list_order: 2,
    is_hidden: 0,
    is_done: 0,
    parent_id: 2,
    url_parent_id: 2,
  },
  {
    id: 5,
    name: "Accounts",
    description: "Accounts",
    slug: "accounts",
    url: "/admin/accounts",
    icon: "users",

    list_order: 12,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 6,
    name: "Clients",
    description: "Clients",
    slug: "clients",
    url: "/admin/accounts/clients",
    icon: "user",

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 5,
    url_parent_id: 5,
  },
  {
    id: 7,
    name: "Administrators",
    description: "",
    slug: "administrators",
    url: "/admin/accounts/administrators",
    icon: "universal-access",

    list_order: 2,
    is_hidden: 0,
    is_done: 1,
    parent_id: 5,
    url_parent_id: 5,
  },
  {
    id: 8,
    name: "Profile",
    description: "",
    slug: "profile",
    url: "/admin/profile",
    icon: "user",

    list_order: 2,
    is_hidden: 1,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 9,
    name: "Settings",
    description: "",
    slug: "settings",
    url: "/admin/settings",
    icon: "cogs",

    list_order: 16,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 10,
    name: "Navigation",
    description: "",
    slug: "navigations",
    url: "/admin/settings/navigations",
    icon: "align-center",
    help_index_title: "Help",
    help_index_content: "Helpful text here - explaining what u can do here...",
    help_create_title: "Information",
    help_create_content: "Please complete the form to create the navigation",
    help_edit_title: "",
    help_edit_content: "",
    list_order: 3,
    is_hidden: 0,
    is_done: 1,
    parent_id: 9,
    url_parent_id: 9,
  },
  {
    id: 11,
    name: "Navigation Order",
    description: "Navigation Order",
    slug: "order",
    url: "/admin/settings/navigations/order",
    icon: "list-ol",

    list_order: 1,
    is_hidden: 1,
    is_done: 0,
    parent_id: 10,
    url_parent_id: 10,
  },
  {
    id: 12,
    name: "Roles",
    description: "Roles",
    slug: "roles",
    url: "/admin/settings/roles",
    icon: "universal-access",

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 9,
    url_parent_id: 9,
  },
  {
    id: 13,
    name: "Settings",
    description: "Settings",
    slug: "settings",
    url: "/admin/settings/settings",
    icon: "cog",

    list_order: 2,
    is_hidden: 0,
    is_done: 0,
    parent_id: 9,
    url_parent_id: 9,
  },
  {
    id: 14,
    name: "Templates",
    description: "Tempplates",
    slug: "templates",
    url: "/admin/settings/templates",
    icon: "file-alt",

    list_order: 4,
    is_hidden: 0,
    is_done: 0,
    parent_id: 9,
    url_parent_id: 9,
  },
  {
    id: 15,
    name: "Layouts",
    description: "Layouts",
    slug: "layouts",
    url: "/admin/settings/layouts",
    icon: "copy",

    list_order: 5,
    is_hidden: 0,
    is_done: 0,
    parent_id: 9,
    url_parent_id: 9,
  },
  {
    id: 16,
    name: "Pages",
    description: "Pages",
    slug: "pages",
    url: "/admin/pages",
    icon: <Layers />,

    list_order: 6,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 17,
    name: "Banners",
    description: "Banners",
    slug: "banners",
    url: "/admin/banners",
    icon: <ViewCarousel />,

    list_order: 4,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 18,
    name: "Analytics",
    description: "Website Analytics",
    slug: "analytics",
    url: "/admin/analytics",
    icon: "chart-line",

    list_order: 15,
    is_hidden: 0,
    is_done: 0,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 19,
    name: "Summary",
    description: "Analytics Summary",
    slug: "summary",
    url: "/admin/analytics/summary",
    icon: "star-half-alt",

    list_order: 1,
    is_hidden: 0,
    is_done: 0,
    parent_id: 18,
    url_parent_id: 18,
  },
  {
    id: 20,
    name: "Devices",
    description: "Analytics on Devices used",
    slug: "devices",
    url: "/admin/analytics/devices",
    icon: "mobile-alt",

    list_order: 2,
    is_hidden: 0,
    is_done: 0,
    parent_id: 18,
    url_parent_id: 18,
  },
  {
    id: 21,
    name: "Visits and Referrals",
    description: "Visits and Referrals",
    slug: "visits-and-referrals",
    url: "/admin/analytics/visits-and-referrals",
    icon: "link",

    list_order: 3,
    is_hidden: 0,
    is_done: 0,
    parent_id: 18,
    url_parent_id: 18,
  },
  {
    id: 22,
    name: "Interests",
    description: "Interests",
    slug: "interests",
    url: "/admin/analytics/interests",
    icon: "heart",

    list_order: 4,
    is_hidden: 0,
    is_done: 0,
    parent_id: 18,
    url_parent_id: 18,
  },
  {
    id: 23,
    name: "Demographics",
    description: "Demographics",
    slug: "demographics",
    url: "/admin/analytics/demographics",
    icon: "female",

    list_order: 5,
    is_hidden: 0,
    is_done: 0,
    parent_id: 18,
    url_parent_id: 18,
  },
  {
    id: 24,
    name: "Resources",
    description: "Resources",
    slug: "resources",
    url: "/admin/resources",
    icon: <Source />,

    list_order: 7,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 25,
    name: "Categories",
    description: "Categories",
    slug: "categories",
    url: "/admin/resources/categories",
    icon: <Category />,

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 26,
    name: "Photos",
    description: "Photos",
    slug: "photos",
    url: "/admin/resources/photos",
    icon: <Camera />,

    list_order: 2,
    is_hidden: 0,
    is_done: 1,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 27,
    name: "Videos",
    description: "Videos",
    slug: "videos",
    url: "/admin/resources/videos",
    icon: <Slideshow />,

    list_order: 3,
    is_hidden: 0,
    is_done: 0,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 28,
    name: "Documents",
    description: "Documents",
    slug: "documents",
    url: "/admin/resources/documents",
    icon: <PictureAsPdf />,

    list_order: 4,
    is_hidden: 0,
    is_done: 0,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 29,
    name: "Reports",
    description: "Reports",
    slug: "reports",
    url: "/admin/reports",
    icon: "file-alt",

    list_order: 14,
    is_hidden: 0,
    is_done: 0,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 30,
    name: "Contact Us",
    description: "Contact Us",
    slug: "contact-us",
    url: "/admin/reports/contact-us",
    icon: "comments",

    list_order: 1,
    is_hidden: 0,
    is_done: 0,
    parent_id: 29,
    url_parent_id: 29,
  },
  {
    id: 31,
    name: "News",
    description: "News",
    slug: "news",
    url: "/admin/news",
    icon: <Newspaper />,

    list_order: 8,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 32,
    name: "Collections",
    description: "Collections",
    slug: "collections",
    url: "/admin/news/collections",
    icon: <Queue />,

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 31,
    url_parent_id: 31,
  },
  {
    id: 33,
    name: "Articles",
    description: "Articles",
    slug: "articles",
    url: "/admin/news/articles",
    icon: <Article />,

    list_order: 2,
    is_hidden: 0,
    is_done: 1,
    parent_id: 31,
    url_parent_id: 31,
  },
  {
    id: 34,
    name: "Shop",
    description: "Shop",
    slug: "shop",
    url: "/admin/shop",
    icon: <Store />,

    list_order: 11,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 35,
    name: "Status",
    description: "Status",
    slug: "status",
    url: "/admin/shop/status",
    icon: <OnlinePrediction />,

    list_order: 1,
    is_hidden: 0,
    is_done: 0,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 36,
    name: "Categories",
    description: "Categories",
    slug: "categories",
    url: "/admin/shop/categories",
    icon: <Category />,

    list_order: 2,
    is_hidden: 0,
    is_done: 1,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 37,
    name: "Features",
    description: "Features",
    slug: "features",
    url: "/admin/shop/features",
    icon: <Star />,

    list_order: 3,
    is_hidden: 0,
    is_done: 1,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 38,
    name: "Products",
    description: "Products",
    slug: "products",
    url: "/admin/shop/products",
    icon: <ShoppingCart />,

    list_order: 4,
    is_hidden: 0,
    is_done: 1,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 39,
    name: "Orders",
    description: "Orders",
    slug: "transactions",
    url: "/admin/shop/transactions",
    icon: <ShoppingBag />,

    list_order: 5,
    is_hidden: 0,
    is_done: 0,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 40,
    name: "Searches",
    description: "Searches",
    slug: "searches",
    url: "/admin/shop/searches",
    icon: <Search />,

    list_order: 6,
    is_hidden: 0,
    is_done: 0,
    parent_id: 34,
    url_parent_id: 34,
  },
  {
    id: 41,
    name: "FAQs",
    description: "question-circle",
    slug: "faqs",
    url: "/admin/faqs",
    icon: <LiveHelp />,

    list_order: 10,
    is_hidden: 0,
    is_done: 0,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 42,
    name: "Categories",
    description: "Categories",
    slug: "categories",
    url: "/admin/faqs/categories",
    icon: <Category />,

    list_order: 1,
    is_hidden: 0,
    is_done: 0,
    parent_id: 41,
    url_parent_id: 41,
  },
  {
    id: 43,
    name: "Questions",
    description: "Questions",
    slug: "questions",
    url: "/admin/faqs/questions",
    icon: <QuestionAnswer />,

    list_order: 2,
    is_hidden: 0,
    is_done: 0,
    parent_id: 41,
    url_parent_id: 41,
  },
  {
    id: 44,
    name: "Comments",
    description: "Comments",
    slug: "comments",
    url: "/admin/news/comments",
    icon: <MarkUnreadChatAlt />,

    list_order: 13,
    is_hidden: 0,
    is_done: 1,
    parent_id: 31,
    url_parent_id: 21,
  },
  {
    id: 45,
    name: "Locations",
    description: "Locations",
    slug: "locations",
    url: "/admin/resources/locations",
    icon: <Map />,

    list_order: 5,
    is_hidden: 0,
    is_done: 0,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 46,
    name: "Menus",
    description: "Menus",
    slug: "menus",
    url: "/admin/menus",
    icon: <List />,

    list_order: 5,
    is_hidden: 0,
    is_done: 1,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 47,
    name: "Texts",
    description: "letter",
    slug: "texts",
    url: "/admin/resources/texts",
    icon: <TextFormat />,

    list_order: 6,
    is_hidden: 0,
    is_done: 0,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 49,
    name: "Content",
    description: "Content",
    slug: "content",
    url: "/admin/resources/content",
    icon: <Inventory />,

    list_order: 7,
    is_hidden: 0,
    is_done: 0,
    parent_id: 24,
    url_parent_id: 24,
  },
  {
    id: 51,
    name: "Themes",
    description: "Themes",
    slug: "themes",
    url: "/admin/themes",
    icon: <PaletteSharp />,

    list_order: 9,
    is_hidden: 0,
    is_done: 0,
    parent_id: 0,
    url_parent_id: 0,
  },
  {
    id: 52,
    name: "Categories",
    description: "Categories",
    slug: "categories",
    url: "/admin/resources/locations/categories",
    icon: <Category />,

    list_order: 999,
    is_hidden: 0,
    is_done: 0,
    parent_id: 45,
    url_parent_id: 45,
  },
  {
    id: 53,
    name: "Location",
    description: "Location",
    slug: "location",
    url: "/admin/resources/locations/location",
    icon: "map-marker-alt",

    list_order: 999,
    is_hidden: 0,
    is_done: 0,
    parent_id: 45,
    url_parent_id: 45,
  },
  {
    id: 54,
    name: "Tags",
    description: "Tags",
    slug: "tags",
    url: "/admin/news/tags",
    icon: <Sell />,

    list_order: 1,
    is_hidden: 0,
    is_done: 1,
    parent_id: 31,
    url_parent_id: 31,
  },
];

export default sideBarItem;

